from __future__ import annotations

from .stage_teacher_precompute import (
    INACTIVE_LOGIT,
    CompletedLogitsRows,
    DistillationMode,
    TeacherLogitsGenerator,
    _assert_teacher_logits_answer_length,
    _compact_adaptive_generation_scores,
    _entropy_to_weight,
    _extract_generated_ids_and_scores,
    _flatten_generated_ids,
    _is_valid_logits_row,
    _load_completed_ids,
    _load_completed_teacher_rows,
    _mock_answer_only_logits_payload,
    _resolve_teacher_logits_mode,
    compute_teacher_forced_answer_logits,
    create_teacher_logits_dataset,
    create_teacher_precompute_dataset,
)

__all__ = [
    "INACTIVE_LOGIT",
    "CompletedLogitsRows",
    "DistillationMode",
    "TeacherLogitsGenerator",
    "_assert_teacher_logits_answer_length",
    "_compact_adaptive_generation_scores",
    "_entropy_to_weight",
    "_extract_generated_ids_and_scores",
    "_flatten_generated_ids",
    "_is_valid_logits_row",
    "_load_completed_ids",
    "_load_completed_teacher_rows",
    "_mock_answer_only_logits_payload",
    "_resolve_teacher_logits_mode",
    "compute_teacher_forced_answer_logits",
    "create_teacher_logits_dataset",
    "create_teacher_precompute_dataset",
]
